---
language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - master
    - /^travis.*/
    - /.*-doc$/

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request
  - name: deploy docs
    if: (branch = master OR branch =~ ^.*-doc$) AND type != pull_request

jobs:
  include:
    - stage: test
      # Build everything before trying to test, otherwise the first set of tests will have no coverage data
      install: ./gradlew jvmTestClasses
      script:
        - ./gradlew jvmTest --tests "animatedledstrip.test.animations.*"
        - mv build/reports/jacoco/test/jacocoTestReport.xml build/reports/jacoco/test/jacocoTestReport-animations.xml
        - ./gradlew jvmTest --tests "animatedledstrip.test.colors.*"
        - mv build/reports/jacoco/test/jacocoTestReport.xml build/reports/jacoco/test/jacocoTestReport-colors.xml
        - ./gradlew jvmTest --tests "animatedledstrip.test.communication.*"
        - mv build/reports/jacoco/test/jacocoTestReport.xml build/reports/jacoco/test/jacocoTestReport-communication.xml
        - ./gradlew jvmTest --tests "animatedledstrip.test.leds.*"
        - mv build/reports/jacoco/test/jacocoTestReport.xml build/reports/jacoco/test/jacocoTestReport-leds.xml
      after_success: bash <(curl -s https://codecov.io/bash)

    #    - stage: deploy
    #      install: skip
    #      script: skip
    #      deploy:
    #        - provider: script
    #          script: mvn deploy -f parent-pom/pom.xml --settings .maven.xml -DskipBuild=true -B

    - stage: deploy
      install: skip
      script: skip
      deploy:
        - provider: script
          script: ./gradlew publish --stacktrace -i

    - stage: deploy docs
      install: skip
      script: skip
      before_script:
        - "DEPLOY_DOCS=$(./gradlew properties | grep '^version:' | sed 's/version: //g' | grep -v SNAPSHOT) || echo 'Snapshot detected, skipping doc deploy'"
      before_deploy:
        - ./gradlew dokkaHtml
        - git add -f dokka
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          verbose: true
          local_dir: ./dokka
          on:
            condition: $DEPLOY_DOCS

    - stage: deploy docs
      install: ./gradlew jvmJar
      script: skip
      before_script:
        - "DEPLOY_DOCS=$(./gradlew properties | grep '^version:' | sed 's/version: //g' | grep -v SNAPSHOT) || echo 'Snapshot detected, skipping doc deploy'"
        - KERMIT_JAR="$(find ~/.gradle -name "kermit-jvm-*.jar")"
      before_deploy:
        - curl -s https://get.sdkman.io | bash
        - source "/home/travis/.sdkman/bin/sdkman-init.sh"
        - sdk install kotlin
        - git clone https://github.com/AnimatedLEDStrip/AnimatedLEDStrip.wiki.git wiki
        - "VERSION=$(./gradlew properties | grep '^version:' | sed 's/version: //g')"
        - kotlinc-jvm -script create_docs.kts -cp "build/libs/animatedledstrip-core-jvm-${VERSION}.jar:$KERMIT_JAR"
        - cd wiki
        - git add .
        - git commit --allow-empty -m "Update animation documentation"
      deploy:
        - provider: script
          script: git push -u https://maxnz:$GITHUB_TOKEN@github.com/AnimatedLEDStrip/AnimatedLEDStrip.wiki.git master
          skip_cleanup: true
          on:
            all_branches: true
            condition: $DEPLOY_DOCS
