---
language: java

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
#  - mvn install -f parent-pom/pom.xml -DskipBuild=true -B

branches:
  only:
    - master
    - /^travis.*/
    - /.*-doc$/

stages:
  - name: test
  - name: deploy
    if: (branch = master OR branch =~ ^.*-doc$) AND type != pull_request

jobs:
  include:
    - stage: test
      install: skip
      script:
#        - ./gradlew jvmTest --tests "animatedledstrip.test.animations.*"
        #        - ./gradlew jvmTest --tests "animatedledstrip.test.colors.*"
        #        - ./gradlew jvmTest --tests "animatedledstrip.test.communication.*"
        - ./gradlew jvmTest --tests "animatedledstrip.test.leds.*" -d
        - ls -l build/jacoco/jvmTest.exec
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      install: skip
      script: skip
      deploy:
        - provider: script
          script: mvn deploy -f parent-pom/pom.xml --settings .maven.xml -DskipBuild=true -B
        - provider: script
          script: mvn deploy -f pom.xml --settings .maven.xml -DskipTests=true -Ddokka=true -B

    - stage: deploy
      install: skip
      script: skip
      before_script:
        - DEPLOY_DOCS=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null | grep -v SNAPSHOT) || echo "Snapshot detected, skipping doc deploy"
      deploy:
        - provider: script
          script: mvn site --settings .maven.xml -DskipTests=true -Ddokka=true -B && git add -f dokka
          on:
            condition: $DEPLOY_DOCS
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          verbose: true
          local_dir: ./dokka
          on:
            condition: $DEPLOY_DOCS

    - stage: deploy docs
      install: mvn package --settings .maven.xml -DskipTests=true -Dshade=true -B
      script: skip
      before_script:
        - DEPLOY_DOCS=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null | grep -v SNAPSHOT) || echo "Snapshot detected, skipping doc deploy"
      before_deploy:
        - curl -s https://get.sdkman.io | bash
        - source "/home/travis/.sdkman/bin/sdkman-init.sh"
        - sdk install kotlin
        - git clone https://github.com/AnimatedLEDStrip/AnimatedLEDStrip.wiki.git wiki
        - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null) # TODO Use gradle
        - kotlinc-jvm -script create_docs.kts -cp build/libs/animatedledstrip-core-jvm-${VERSION}.jar
        - cd wiki
        - git add .
        - git commit --allow-empty -m "Update animation documentation"
      deploy:
        - provider: script
          script: git push -u https://maxnz:$GITHUB_TOKEN@github.com/AnimatedLEDStrip/AnimatedLEDStrip.wiki.git master
          skip_cleanup: true
          on:
            all_branches: true
            condition: $DEPLOY_DOCS
