---
language: java
jdk: openjdk9

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

branches:
  only:
    - master
    - /^travis/
    - /^v.*/

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      install: true
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      install:
      - ""
      deploy:
        - provider: script
          script: mvn --settings .maven.xml site -DskipTests=true -B && git add dokka
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
    - stage: deploy
      if: branch = master OR branch = /v.*/
      install:
      - ""
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B



