---
language: java

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

install:
  mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

#script:
#  mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease

branches:
  only:
    - master
    - /^travis/
    - /^v.*/

stages:
  - name: test
  - name: deploy gh-pages
  - name: deploy snapshot
    if: env(project_version) =~ ^.*-SNAPSHOT$

jobs:
  include:
    - stage: test
    - stage: deploy gh-pages
      before_deploy: mvn dokka:dokka
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
#      deploy:
#      - provider: script
#        script: mvn site --settings .maven.xml -B
#        on:
#          branch: master
    - stage: deploy snapshot
      deploy:
      - provider: script
        script: mvn deploy --settings .maven.xml -B
        on:
          branch: master

