---
language: java
jdk: openjdk9

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

branches:
  only:
    - master
    - /^travis.*/
    - /^v.*/

stages:
  - name: test
  - name: deploy snapshot
    if: branch = master AND type != pull_request
  - name: deploy release
    if: branch =~ ^v.*$

jobs:
  include:
    - stage: test
      install: skip
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: deploy release
      install: skip
      script: skip
      deploy:
        - provider: script
          script: mvn --settings .maven.xml site -DskipTests=true -B && git add dokka
          on:
            tags: true
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
          on:
            all_branches: true

    - stage: deploy release
      install: skip
      script: skip
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B
          on:
            all_branches: true

    - stage: deploy snapshot
      install: skip
      script: skip
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B
          on:
            branch: master
