---
language: java
jdk: openjdk9

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

branches:
  only:
    - master
    - /^travis.*/
    - /^v.*/

stages:
  - name: test
  - name: deploy snapshot
    if: branch = master AND type != pull_request
  - name: deploy release
    if: branch =~ ^v.*$
  - name: deploy docs
    if: (branch = master AND type != pull_request) OR branch =~ ^.*-doc$

jobs:
  include:
    - stage: test
      install: skip
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: deploy release
      install: skip
      script: skip
      deploy:
        - provider: script
          script: mvn site --settings .maven.xml -DskipTests=true -DdoDokka=true -B && git add dokka
          on:
            all_branches: true
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          verbose: true
          local_dir: ./dokka
          on:
            all_branches: true

    - stage: deploy release
      install: skip
      script: skip
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B
          on:
            all_branches: true

    - stage: deploy snapshot
      install: skip
      script: skip
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -B
          on:
            branch: master

    - stage: deploy docs
      install: mvn package --settings .maven.xml -DskipTests=true -Dshade=true -B
      script: skip
      before_deploy:
        - curl -s https://get.sdkman.io | bash
        - source "/home/travis/.sdkman/bin/sdkman-init.sh"
        - sdk install kotlin
        - git clone https://github.com/AnimatedLEDStrip/AnimatedLEDStrip.wiki.git wiki
        - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null)
        - kotlinc-jvm -script create_docs.kts -cp target/animatedledstrip-core-${VERSION}.jar -- ${VERSION}
        - cd wiki
        - git add .
        - git commit -m "Update animation documentation"
      deploy:
        - provider: script
          script: git push -u https://maxnz:$GITHUB_TOKEN@github.com/AnimatedLEDStrip/AnimatedLEDStrip.wiki.git master
          skip_cleanup: true
          on:
            all_branches: true
