name: Publish to Maven Central

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13

    - name: Publish to Maven Central
      run: ./gradlew publish --stacktrace
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
        ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}

  deploy-documentation:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Create documentation
        run: |
          ./gradlew dokkaHtml
          git add -f dokka

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dokka
          clean: false

  deploy-anim-documentation:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install kotlin compiler
        uses: sdkman/sdkman-action@master
        with:
          candidate: kotlin
          version: 1.4.30

      - name: Create JVM Jar
        run: ./gradlew jvmJar

      - name: Clone wiki
        run: git clone https://github.com/AnimatedLEDStrip/AnimatedLEDStrip.wiki.git wiki

      - name: Create documentation
        run: |
          KERMIT_JAR="$(find ~/.gradle -name "kermit-jvm-*.jar")"
          kotlinc-jvm -script create_docs.kts -cp "build/libs/animatedledstrip-core-jvm-${VERSION}.jar:$KERMIT_JAR"

      - name: Upload Documentation to Wiki
        run: |
          cd wiki
          git add .
          git commit --allow-empty -m "Update animation documentation"
          git push -u https://$GH_PAT_USER:$GH_PERSONAL_ACCESS_TOKEN@github.com/AnimatedLEDStrip/AnimatedLEDStrip.wiki.git master
        env:
          GH_PAT_USER: ${{ secrets.GH_PAT_USER }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
