name: publish-snapshot

on:
  push:
    branches: [ master ]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: version_number
        run: "echo \"::set-output name=als_version::$(./gradlew properties | grep '^version:' | sed 's/version: //g')\""

      - name: Publish to Maven Snapshots
        if: endsWith(steps.version_number.outputs.als_version, "-SNAPSHOT")
        run: ./gradlew publish --stacktrace
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
