name: Publish to Maven Central

on:
  release:
    types: [ created ]
  push:
    branches: [ gh-action-fix-publish ]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

  #      - name: Publish to Maven Central
  #        run: ./gradlew publish --stacktrace
  #        env:
  #          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
  #          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
  #          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
  #          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}

  deploy-documentation:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Create documentation
        run: |
          ./gradlew dokkaHtml
          git add -f dokka

  #      - name: Deploy documentation
  #        uses: JamesIves/github-pages-deploy-action@4.0.0
  #        with:
  #          branch: gh-pages
  #          folder: dokka
  #          clean: false

  deploy-anim-documentation:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v2
      - name: Install python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            argparse
            pillow
            tqdm

      - name: Update script dependencies
        run: scripts/update-script-dependencies.bash

      - name: Prepare pages and signatures for upload
        run: scripts/commit-animation-docs.bash

#      - name: Upload documentation
#        uses: ad-m/github-push-action@v0.6.0
#        with:
#          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
#          directory: wiki
#          repository: AnimatedLEDStrip/animatedledstrip.github.io
